CREATE TABLE SPORTISTA
(
    ID NUMBER(5) CONSTRAINT SPORTISTA_PK PRIMARY KEY,
    IME VARCHAR(30),
    PREZIME VARCHAR(30),
    BRTEL VARCHAR(15),
    GOD_ROD NUMBER(4) CONSTRAINT GOD_ROD_CK CHECK (GOD_ROD BETWEEN 1970 AND 2010),
    GRAD VARCHAR(30), 
    PLATA NUMBER(7)
);

CREATE TABLE KLUB
(
    ID NUMBER(5) CONSTRAINT KLUB_PK PRIMARY KEY,
    NAZIV VARCHAR(40) NOT NULL,
    LOKACIJA VARCHAR(40),
    GOD_OSNIVANJA NUMBER(4),
    SPORT VARCHAR(40)
);

CREATE TABLE CLAN
(
    ID NUMBER(5) CONSTRAINT CLAN_PK PRIMARY KEY,
    ID_SPORTISTE NUMBER(5) REFERENCES SPORTISTA(ID),
    ID_KLUBA NUMBER(5) REFERENCES KLUB(ID),
    DATUM_OD DATE NOT NULL,
    DATUM_DO DATE,
    TIM VARCHAR(10) CONSTRAINT TIM_CK CHECK (TIM = 'skola' OR TIM = 'prvi' OR TIM = 'mladi')
);