CREATE TABLE BIRACKO_MESTO
(
    ID NUMBER(5) CONSTRAINT BIRACKO_MESTO_PK PRIMARY KEY,
    OPSTINA VARCHAR(50),
    R_BROJ NUMBER(5),
    ADRESA VARCHAR(50),
    UKUPNO_GLASACA NUMBER(10) NOT NULL,
    UKUPNO_LISTICA NUMBER(12) NOT NULL,
    VAZECI_LISTICI NUMBER(10),
    NEVAZECI_LISTICI NUMBER(10)
);

CREATE TABLE UCESNIK
(
    ID NUMBER(5) CONSTRAINT UCESNIK_PK PRIMARY KEY,
    NAZIV VARCHAR(50),
    NOSILAC_LISTE VARCHAR(50),
    REDNI_BROJ NUMBER(3)
);

CREATE TABLE REZULTATI
(
    ID_BIRACKO_MESTO NUMBER(5) REFERENCES BIRACKO_MESTO(ID),
    ID_UCESNIK NUMBER(5) REFERENCES UCESNIK(ID),
    BROJ_GLASOVA NUMBER(12)
);