CREATE TABLE KOMPANIJA
(
    ID NUMBER(5) CONSTRAINT KOMPANIJA_PK PRIMARY KEY,
    NAZIV VARCHAR(40) NOT NULL,
    ULICA VARCHAR(40),
    BROJ NUMBER(4),
    GRAD VARCHAR(30) NOT NULL,
    POSTANSKI_BROJ NUMBER(6),
    DRZAVA VARCHAR(30) NOT NULL,
    PIB NUMBER(10) NOT NULL
);

CREATE TABLE RACUN
(
    ID NUMBER(5) CONSTRAINT RACUN_PK PRIMARY KEY,
    DAT_PLACANJA DATE,
    DAT_KREIRANJA DATE,
    VALUTA CHAR(3) CONSTRAINT VALUTA_CK CHECK (VALUTA = 'EUR' OR VALUTA = 'RSD'),
    IZNOS NUMBER(10),
    POREZ NUMBER(10),
    KOMP_SALJE NUMBER(5) REFERENCES KOMPANIJA(ID),
    KOMP_PRIMA NUMBER(5) REFERENCES KOMPANIJA(ID)
);

CREATE TABLE KNJIZNOODOBRENJE
(
    ID NUMBER(5) CONSTRAINT KNJIZNOODOBRENJE_PK PRIMARY KEY,
    DAT_KREIRANJA DATE,
    UM_IZNOS NUMBER(10),
    UM_POREZ NUMBER(10),
    ID_RACUNA NUMBER(5) REFERENCES RACUN(ID)
);